replica:
  id: ${REPLICA_ID:1}
  urls: http://localhost:12348,http://localhost:12346, http://localhost:12347

catalog:
  service:
    url: http://localhost:12345

start: 0

frontend:
  service:
    url: http://localhost:12343
server:
  port: 12346
